import React from 'react';
import './globals.sass';
import { Mukta } from 'next/font/google';
import Provider from './provider';
import DarkModeBtn from './components/DarkModeBtn';

const inter = Mukta({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500'],
});

export const metadata = {
  title: 'Where in the world?',
  description: 'Generated by create next app',
};
type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  const html = (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <header className="px-3 py-7 p-lg-7 shadow">
            <div className="container mx-auto">
              <div className="flex w-10/12 md:w-10/12 lg:w-full mx-auto  justify-between">
                <div className="flex-grow w-50 w-lg-80">
                  <h1 className="text-xl font-bold">
                    {metadata.title}
                  </h1>
                </div>
                <DarkModeBtn />
              </div>
            </div>
          </header>
          <main className="container mx-auto">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
  return html;
};
export default RootLayout;
