import React from 'react';
import './globals.sass';
import { Mukta } from 'next/font/google';
import Provider from './provider';
import DarkModeBtn from './components/DarkModeBtn';

const inter = Mukta({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500'],
});

export const metadata = {
  title: 'Where in the world?',
  description: 'Generated by create next app',
};
type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  const html = (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <header className="flex shadow justify-between px-3 py-7 p-lg-7">
            <div className="flex-grow w-50 w-lg-80">
              <h1 className="text-xl font-bold">
                {metadata.title}
              </h1>
            </div>
            <DarkModeBtn />
          </header>
          <main className="container mx-auto">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
  return html;
};
export default RootLayout;
