import React from 'react';
import './globals.sass';
import { Inter } from 'next/font/google';
import Provider from './provider';
import DarkModeBtn from './components/DarkModeBtn';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC = ({ children }) => {
  const html = (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <DarkModeBtn />
          <main className="container mx-auto">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
  return html;
};
export default RootLayout;
